pipeline {
    agent {
        label 'node.js'
    }
    stages {
        stage('github') {
            steps {
                git branch: 'main', credentialsId: 'd15798d4-dfa9-4d95-80fa-166ff008a415', url: 'https://github.com/AbdElRhmanArafa/nodjs-mysql-crud-project-master'
            }
        }
        stage('Install Dependencies') {
            steps {
                // Use 'npm ci' to install the project dependencies (faster and more reliable for CI)
                sh 'npm ci'
            }
        }
        stage('Build') {
            steps {
                sh 'npm run start &'
            }
        }
    }

    post {
        success {
            // send massage to slack channel
            echo 'Build succeeded. Deploying...'
        }
        failure {
              echo 'Build failed. Sending notifications...'
        }
    }
}

