pipeline {
    agent {
        label 'node.js'
    }
    stages {
        stage('github') {
            steps { 
                git branch: 'main', credentialsId: 'd15798d4-dfa9-4d95-80fa-166ff008a415', url: 'https://github.com/AbdElRhmanArafa/nodjs-mysql-crud-project-master'
            }
        }
    }
}
